/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eandd.tungbt94.View;

import eandd.tungbt94.Control.Connection;
import eandd.tungbt94.Control.Control;
import eandd.tungbt94.Model.Post;
import eandd.tungbt94.Model.Title;
import eandd.tungbt94.Model.TitlePrimary;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Bui Thanh Tung
 */
public class FrameTitlePrimary extends javax.swing.JFrame implements ActionListener{

    private Connection connection;
    private Control control;
    private ArrayList<Title> arrTitle;

    public void setControl(Control control) {
        this.control = control;
    }
    
    /**
     * Creates new form TitlePrimary
     */
    public FrameTitlePrimary() {
        initComponents();
        btnRead.addActionListener(this);
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
//        loadTable();
    }

    public void setConnection(Connection connection) {
        this.connection = connection;
    }
    
    public void loadName(String name) {
        lbName.setText(name);
    }

    public void loadTable(TitlePrimary titlePrimary) {
        TableModel tbTitlePrimary = new DefaultTableModel(getData(), getColumnName()) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblTitlePrimary.setModel(tbTitlePrimary);
        tblTitlePrimary.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblTitlePrimary.getColumnModel().getColumn(0).setPreferredWidth(300);
        tblTitlePrimary.getColumnModel().getColumn(1).setPreferredWidth(300);
        tblTitlePrimary.getColumnModel().getColumn(2).setPreferredWidth(300);
        tblTitlePrimary.getColumnModel().getColumn(3).setPreferredWidth(300);
    }

    private Object[] getColumnName() {
        return new Object[]{"Title", "Href","Lead","Avatar"};
    }

    private Object[][] getData() {
        arrTitle = connection.getListTitle();
        int size = arrTitle.size();
        Object[][] data = new Object[size][4];
        for(int i = 0; i < size; i++){
            data[i][0] = arrTitle.get(i).getTitlePost();
            data[i][1] = arrTitle.get(i).getHref();
            data[i][2] = arrTitle.get(i).getLead();
            data[i][3] = arrTitle.get(i).getAvatar();
        }

        return data;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTitlePrimary = new javax.swing.JTable();
        btnRead = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TitlePrimary");
        setPreferredSize(new java.awt.Dimension(1200, 500));

        lbName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbName.setText("TitlePrimary's Name");

        tblTitlePrimary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTitlePrimary);

        btnRead.setText("Read");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRead, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1180, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(btnRead))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrameTitlePrimary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrameTitlePrimary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrameTitlePrimary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrameTitlePrimary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrameTitlePrimary().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRead;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbName;
    private javax.swing.JTable tblTitlePrimary;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource().equals(btnRead)){
            int selectedRow = tblTitlePrimary.getSelectedRow();
            Title title = arrTitle.get(selectedRow);
            control.loadPost(title);
        }
    }
}
